<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            padding: 0;
            font-family: "Trebuchet MS", serif;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: inherit !important;
        }

        #MessageViewBody a {
            color: inherit;
            text-decoration: none;
        }

        p {
            line-height: inherit
        }

        .desktop_hide,
        .desktop_hide table {
            mso-hide: all;
            display: none;
            max-height: 0px;
            overflow: hidden;
        }

        .image_block img + div {
            display: none;
        }

        @media (max-width: 650px) {
            .desktop_hide table.icons-inner {
                display: inline-block !important;
            }

            .icons-inner {
                text-align: center;
            }

            .icons-inner td {
                margin: 0 auto;
            }

            .row-content {
                width: 100% !important;
            }

            .mobile_hide {
                display: none;
            }

            .stack .column {
                width: 100%;
                display: block;
            }

            .mobile_hide {
                min-height: 0;
                max-height: 0;
                max-width: 0;
                overflow: hidden;
                font-size: 0px;
            }

            .desktop_hide,
            .desktop_hide table {
                display: table !important;
                max-height: none !important;
            }
        }
    </style>
</head>
<body style="background-color: #FFFFFF; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">
<table border="0" cellpadding="0" cellspacing="0" class="nl-container" role="presentation"
       style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF;" width="100%">
    <tbody>
    <tr>
        <td>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-1" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="18.333333333333336%">
                                    <div class="spacer_block" style="height:15px;line-height:15px;font-size:1px;"> 
                                    </div>
                                    <table border="0" cellpadding="5" cellspacing="0" class="heading_block block-2"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <h1 style="margin: 0; color: #004da8; direction: ltr; font-family: 'Trebuchet MS','Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif; font-size: 23px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: left; margin-top: 0; margin-bottom: 0;">
                                                    <span class="tinyMce-placeholder">Jamii Plus - APP Business</span>
                                                </h1>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="5" cellspacing="0" class="heading_block block-3"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <h3 style="margin: 0; color: #004da8; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 11px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: left; margin-top: 0; margin-bottom: 0;">
                                                    <span class="tinyMce-placeholder">Business Type :
                                                     <#if isAgent==1>
                                                         Agent Business
                                                     <#else>
                                                         Direct Business
                                                     </#if>
                                                    </span>
                                                </h3>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-3"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="25%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                <div align="right" class="alignment" style="line-height:10px"><img
                                                            src="https://www.apainsurance.org/images/AppResources/8VcqfzV.png"
                                                            style="display: block; height: auto; border: 0; width: 158px; max-width: 100%;"
                                                            width="158"/></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-2" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr style="background-color:#004da8;">
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: white; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Client Details</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-3" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="60%">
                                    <table border="0" cellpadding="10" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="60%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong style="font-size:12px;">Name</strong>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong style="font-size:12px;">${holderName}</strong>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong style="font-size:12px;">Email</strong>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong style="font-size:12px;">${holderEmail}</strong>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong>Policy</strong>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                            <strong style="font-size:12px;">${policyNumber}</strong>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Gender</strong>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>${holderGender}</strong>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-4" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="empty_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-5" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr style="background-color:#004da8;">
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: white; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Dependants Details</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-6" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr style="background-color:#004da8;">
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="25%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Name</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-2"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="25%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Relationship</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-3"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="25%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Gender</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-4"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="25%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>DOB</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-7" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <#list dependants>
                                <#items as dep>
                                    <tr>
                                        <td class="column column-1"
                                            style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                            width="25%">
                                            <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                                   role="presentation"
                                                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                                   width="100%">
                                                <tr>
                                                    <td class="pad">
                                                        <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                            <div class=""
                                                                 style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                    ${dep.firstName} ${dep.lastName}</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td class="column column-2"
                                            style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                            width="25%">
                                            <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                                   role="presentation"
                                                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                                   width="100%">
                                                <tr>
                                                    <td class="pad">
                                                        <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                            <div class=""
                                                                 style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                    ${dep.relationshipDesc}</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td class="column column-3"
                                            style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                            width="25%">
                                            <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                                   role="presentation"
                                                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                                   width="100%">
                                                <tr>
                                                    <td class="pad">
                                                        <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                            <div class=""
                                                                 style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                    ${dep.gender}</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td class="column column-4"
                                            style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                            width="25%">
                                            <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                                   role="presentation"
                                                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                                   width="100%">
                                                <tr>
                                                    <td class="pad">
                                                        <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                            <div class=""
                                                                 style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                    ${dep.dateOfBirth?date}</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </#items>
                            <#else>
                                <tr>
                                    <td class="pad">
                                        <div style="font-family: 'Trebuchet MS', sans-serif;">
                                            <div class=""
                                                 style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                <p style="margin: 10px; font-size: 12px; text-align: left; mso-line-height-alt: 14.399999999999999px;">
                                                    <strong>No Dependants</strong></p>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </#list>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-8" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="empty_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-9" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr style="background-color:#004da8;">
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Selected Benefits</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-10" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="50%">
                                    <table border="0" cellpadding="10" cellspacing="0" class="list_block block-1"
                                           id="list-r9c0m0" role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div class="levelOne" style="margin-left: 0;">
                                                    <ul class="leftList"
                                                        style="margin-top: 0; margin-bottom: 0; padding: 0; padding-left: 20px; color: #101112; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0; line-height: 120%; text-align: left; list-style-type: disc;">
                                                        <li style="margin-bottom: 0; text-align: left;">InPatient -
                                                            Ksh. ${benefitValues.inpatientLimit}/- 
                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="10" cellspacing="0" class="list_block block-2"
                                           id="list-r9c0m1" role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div class="levelOne" style="margin-left: 0;">
                                                    <ul class="leftList"
                                                        style="margin-top: 0; margin-bottom: 0; padding: 0; padding-left: 20px; color: #101112; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0; line-height: 120%; text-align: left; list-style-type: disc;">
                                                        <li style="margin-bottom: 0; text-align: left;">OutPatient -
                                                            Ksh. ${benefitValues.outpatientLimit}/-
                                                        </li>
                                                    </ul>
                                                </div>
                                                <div class="levelTwo" style="margin-left: 20px;">
                                                    <ul class="leftList"
                                                        style="margin-top: 0; margin-bottom: 0; padding: 0; padding-left: 20px; color: #101112; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0; line-height: 120%; text-align: left; list-style-type: circle;">
                                                        <li style="margin-top:12px; text-align: left;">Dental -
                                                            Ksh. ${benefitValues.dentalLimit}/-
                                                        </li>
                                                        <li style="margin-top:12px; text-align: left;">Optical -
                                                            Ksh. ${benefitValues.opticalLimit}/-
                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="column column-2"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="50%">
                                    <table border="0" cellpadding="10" cellspacing="0" class="list_block block-1"
                                           id="list-r9c1m0" role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div class="levelOne" style="margin-left: 0;">
                                                    <ul class="leftList"
                                                        style="margin-top: 0; margin-bottom: 0; padding: 0; padding-left: 20px; color: #101112; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0; line-height: 120%; text-align: left; list-style-type: disc;">
                                                        <li style="margin-bottom: 0; text-align: left;">Maternity -
                                                            Ksh. ${benefitValues.maternityLimit}/-
                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="10" cellspacing="0" class="list_block block-2"
                                           id="list-r9c1m1" role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div class="levelOne" style="margin-left: 0;">
                                                    <ul class="leftList"
                                                        style="margin-top: 0; margin-bottom: 0; padding: 0; padding-left: 20px; color: #101112; direction: ltr; font-family: 'Trebuchet MS', sans-serif; font-size: 12px; font-weight: 400; letter-spacing: 0; line-height: 120%; text-align: left; list-style-type: disc;">
                                                        <li style="margin-bottom: 0; text-align: left;">Travel
                                                            - ${(benefit.travelInsurance?string('YES', 'NO')) ! "N/A"}</li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-11" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="empty_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-12" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #004da8; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Premium Payable Ksh. <span style="color:#ff0c0e;">${premium}</span>/-</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-13" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="empty_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-14" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr style="background-color:#004da8;">
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #ffffff; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <strong>Business Type</strong></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-2"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <table border="0" cellpadding="10" cellspacing="0"
                                                       class="text_block block-1"
                                                       role="presentation"
                                                       style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                                       width="60%">
                                                    <tr>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong style="font-size:12px;">Type</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong style="font-size:12px;">Agent
                                                                            Business</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>

                                                    <tr>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong style="font-size:12px;">Name</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong style="font-size:12px;">${agentName}</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong>Branch</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14px;">
                                                                        <strong style="font-size:12px;">${agentBranch} </strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                        <strong>Mobile</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                        <strong>${agentPhoneNumber}</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                        <strong>Email</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="pad">
                                                            <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                                <div class=""
                                                                     style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                                    <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                                        <strong>${agentEmail}</strong>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>

                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-15" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                             </p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-16" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="5" cellspacing="0" class="text_block block-1"
                                           role="presentation"
                                           style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;"
                                           width="100%">
                                        <tr>
                                            <td class="pad">
                                                <div style="font-family: 'Trebuchet MS', sans-serif;">
                                                    <div class=""
                                                         style="font-size: 12px; font-family: 'Trebuchet MS', sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;">
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <span style="color:#c9c6c6;"><em><strong>Regards,</strong></em></span>
                                                        </p>
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                             </p>
                                                        <p style="margin: 0; font-size: 12px; mso-line-height-alt: 14.399999999999999px;">
                                                            <span style="color:#c9c6c6;"><em><strong>Digital Health</strong></em></span>
                                                        </p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-17" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="image_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                <div align="left" class="alignment" style="line-height:10px"><img
                                                            src="https://www.apainsurance.org/images/AppResources/sOPgJxn.png"
                                                            style="display: block; height: auto; border: 0; width: 252px; max-width: 100%;"
                                                            width="252"/></div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
            <table align="center" border="0" cellpadding="0" cellspacing="0" class="row row-18" role="presentation"
                   style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                <tbody>
                <tr>
                    <td>
                        <table align="center" border="0" cellpadding="0" cellspacing="0" class="row-content stack"
                               role="presentation"
                               style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 630px;"
                               width="630">
                            <tbody>
                            <tr>
                                <td class="column column-1"
                                    style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;"
                                    width="100%">
                                    <table border="0" cellpadding="0" cellspacing="0" class="icons_block block-1"
                                           role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                           width="100%">
                                        <tr>
                                            <td class="pad"
                                                style="vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;">
                                                <table cellpadding="0" cellspacing="0" role="presentation"
                                                       style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
                                                       width="100%">
                                                    <tr>
                                                        <td class="alignment"
                                                            style="vertical-align: middle; text-align: center;">

                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>